version: '3.7'

services:
   #api:
   dbtester:
      image: adminer
      ports:
         - "9000:8080"
   db:
      image: kartoza/postgis:11.0-2.5
      ports:
         - "25434:5432"
      env_file:
         - docker-env/db.env
      restart: on-failure
      healthcheck:
        test: "exit 0"
      #volumes:
      #   - ./volumes/GeoDbData:/var/lib/postgresql/data   
   geoserver:
      image: kartoza/geoserver:2.15.0
      volumes:
      -  type: volume
         source: geoserverdata
         target: /opt/geoserver/data_dir/
         consistency: consistent
      -  type: volume
         source: shpfiles
         target: /opt/geoserver/shpfilestmp
         consistency: cached
      ports:
        - "8600:8080"
      restart: on-failure
      env_file:
        - docker-env/geoserver.env
      depends_on:
        - db
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3

volumes:
   geoserverdata:
   shpfiles:
      driver: local
      driver_opts:
         type: none
         device: $PWD/SHPFiles
         o: bind