version: '3.7'

services:
   dbtester:
      image: adminer
      ports:
         - "9000:8080"

   db:
      image: kartoza/postgis:11.0-2.5
      container_name: 'mainPostgres'
      ports:
         - "25434:5432"
      env_file:
         - docker-env/db.env
      restart: on-failure
      healthcheck:
        test: "exit 0"
      #volumes:
      #   - ./volumes/GeoDbData:/var/lib/postgresql/data   
      

   geoserver:
      container_name: 'geoservertester'
      build: 
         context: ./dockerImages
         dockerfile: geoserver.dockerfile
      volumes:
      -  type: volume
         source: geoserverdata
         target: /opt/geoserver/data_dir/
         consistency: consistent
      ports:
        - "8600:8080"
      restart: on-failure
      env_file:
        - docker-env/geoserver.env
      depends_on:
        - db
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
#   javabridge:
#      container_name: 'distApi'
#      build: 
#         context: ./
#         dockerfile: javaApi.dockerfile
#      ports:
#         - "8800:8080"



volumes:
   geoserverdata:
