version: '3.7'

services:      
   geoserver:
      container_name: 'geoservertester'
      hostname: 'geoservertester'
      build: 
         context: ./dockerImages
         dockerfile: geoserver.dockerfile
      volumes:
      -  type: volume
         source: geoserverdata
         target: /opt/geoserver/data_dir/
         consistency: consistent
      ports:
        - "8600:8080"
      restart: on-failure
      env_file:
        - docker-env/geoserver.env
      #depends_on:
      #  - db
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3 
   
volumes:
   geoserverdata:
