version: '3.7'
services:
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: 'citusdata/membership-manager:0.2.0'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    command: ["sh" ,"-c", "sleep 130s && python -u ./manager.py"]

  