version: '3.7'
services:
  master:
    #container_name: "${COMPOSE_PROJECT_NAME}_master"
    image: 'democustom:m'
    #build: 
    #  context: ./dockerImages
    #  dockerfile: citusmaster.dockerfile
    ports: ["${MASTER_EXTERNAL_PORT:-5432}:5432"]
    labels: ['com.citusdata.role=Master']
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 35s
      timeout: 5s
      retries: 14
      start_period: 120s
  
