version: '3.7'
services:
  worker:
    #build: 
    #  context: ./dockerImages
    #  dockerfile: citusworker.dockerfile
    image: 'democustom:w'
    labels: ['com.citusdata.role=Worker']
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 35s
      timeout: 5s
      retries: 14
      start_period: 120s
  
